version: "3.7"
networks:
  wp:

services:
  &db-service wp-mysql:
    container_name: *db-service
    hostname: *db-service
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: wp-database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: &MYSQL_ROOT_PASS passwordroot
    networks:
      - wp
  &pma-service wp-pma:
    container_name: *pma-service
    hostname: *pma-service
    restart: always
    depends_on:
      - *db-service
    image: phpmyadmin:latest
    environment:
      PMA_HOST: *db-service
      MYSQL_ROOT_PASSWORD: *MYSQL_ROOT_PASS
      UPLOAD_LIMIT: "1G"
    networks:
      - wp
    ports:
      - ${PHPMYADMIN_CONTAINER_PORT}:80
  &apache-service wp-apache:
    container_name: *apache-service
    hostname: *apache-service
    build:
      ./docker/apache
    volumes:
      - ./public:/var/www/html
    restart: always
    networks:
      - wp
    ports:
     - ${APACHE_CONTAINER_PORT}:80
